### PR TITLE
Adding a go.mod, go.sum to blevex

### PR DESCRIPTION
**Pull request by abhinavdangeti**

### CODE REVIEW

**Comment by mschoch** [comment]
We need to slow our roll here.  I think we'll eventually need to also tag versions here so that users of the kvstores inside blevex can work with bleve 1.x and 2.x, which leads to a whole new set of problems.

I would prefer we think through the big picture before rushing into this.

**Comment by abhinavdangeti** [comment]
@mschoch Sure, I was just offering the reason why the "indirect" imports are showing up within bleve's go.mod. Let's take our time with this.

**Comment by mschoch** [comment]
My recollection is that when there are no tags, Go modules will use master.  But that once we create a tag, it will always choose that.  So, that means we'd have to create tag pointing to the current version, and do (you guess it) another release of bleve 1.x using it...

**Comment by abhinavdangeti** [comment]
Yay .. I guess. Haha

Seems like it uses master (the SHA) if there aren't any tags, else by what I'm seeing the latest available tag.

**Comment by abhinavdangeti** [comment]
Updated my previous comment^. (Didn't show up as a notification for some reason)

**Comment by abhinavdangeti** [comment]
Using https://github.com/blevesearch/blevex/pull/49

**Pull request closed without merging**
