### PR TITLE
migrate to github actions

### PR DESCRIPTION
**Pull request by mschoch**

### CODE REVIEW

**Review by abhinavdangeti — APPROVED** [review]

**Comment by mschoch** [comment]
@abhinavdangeti no need to review, this isn't very close yet

**Comment by mschoch** [comment]
@abhinavdangeti ready for review now

**Review by abhinavdangeti — APPROVED** [review]
Lot of threads in TestIndexBatcherConcurrentCrud :)

**Comment by mschoch** [comment]
@abhinavdangeti that was contributed, I just wanted to make the tests pass with the race flag.

**Pull request merged**
