### PR TITLE
migrate to the cockroachdb rocksdb wrapper

### LINKED ISSUE #8: rockdb and go get
your using this github.com/tecbot/gorocksdb

There is i believe a better way. Coockroachdb also need rocks bd, and have written a fully go gettable implementation of rockdb. As i understand it the cockroach team do not need all the the API of rocksdb, so your milage may vary.
This is it:
https://github.com/cockroachdb/c-rocksdb

### PR DESCRIPTION
**Pull request by mschoch**
https://github.com/cockroachdb/c-rocksdb
also added support for pure-C merge functions
fixes #8

### CODE REVIEW

**Comment by mschoch** [comment]
Hold up for this right now is that it doesn't work on windows.

**Comment by mschoch** [comment]
This also makes use of NativeMergeOperator which I had defined in bleve.  I now strongly dislike that this would make use of "unsafe" in the core of bleve.  I am removing that implementation for now, and pasting it here in case it can later be relocated:

```
// NativeMergeOperator is a merge operator that also includeTermVectors
// a C implementation
type NativeMergeOperator interface {
	MergeOperator

	// a pointer to function in C with the signature
	// char* (*full_merge)(void *state,
	//     const char* key, size_t key_length,
	//     const char* existing_value,
	//     size_t existing_value_length,
	//     const char* const* operands_list,
	//     const size_t* operands_list_length, int num_operands,
	//     unsigned char* success, size_t* new_value_length)
	FullMergeC() unsafe.Pointer

	// a pointer to function in C with the signature
	// char* (*partial_merge)(void *state,
	//     const char* key, size_t key_length,
	//     const char* const* operands_list,
	//     const size_t* operands_list_length, int num_operands,
	//     unsigned char* success, size_t* new_value_length)
	PartialMergeC() unsafe.Pointer

	// a pointer to function in C with signature
	// const char* merge_operator_name_fn(void *state)
	NameC() unsafe.Pointer
}
```

**Comment by tmm1** [comment]
Tried using this an ran into a compile error, due to the missing unsafe C impl:

```
# github.com/tmm1/blevex/rocksdb
.go/src/github.com/tmm1/blevex/rocksdb/store.go:75: undefined: store.NativeMergeOperator
```

I removed the code causing the error to fallback to the go merge code, but am getting a runtime error:

```
panic: runtime error: cgo result has Go pointer

goroutine 17 [running, locked to thread]:
panic(0x4754220, 0xc8204470d0)
	/usr/local/Cellar/go/1.6.1/libexec/src/runtime/panic.go:464 +0x3e6
github.com/tmm1/blevex/rocksdb._cgoexpwrap_2014184ded4a_gorocksdb_mergeoperator_partial_merge_multi.func1(0xc820038ec0)
	github.com/tmm1/blevex/rocksdb/_obj/_cgo_gotypes.go:1528 +0x3a
github.com/tmm1/blevex/rocksdb._cgoexpwrap_2014184ded4a_gorocksdb_mergeoperator_partial_merge_multi(0xc8200e0bd0, 0x68397e1, 0x7, 0x6850200, 0x6851e00, 0x35e, 0x70000030d50f, 0x70000030d500, 0xc8204470c8)
	github.com/tmm1/blevex/rocksdb/_obj/_cgo_gotypes.go:1530 +0xbf
```

**Comment by mschoch** [comment]
This branch is largely abandoned at the moment.  Because it doesn't work on windows, its uninteresting to me as anything I would want to build would require that.

When this was last used it was with 1.5.  The regular rocksdb adapter has been tested with Go 1.6.  I think @steveyen ran it just the other day.

**Comment by mschoch** [comment]
Closing, it was never fished and is now too old.

**Pull request closed without merging**
